apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-02-19T10:28:08Z
  name: sample-category
  version: 0.1.0
  annotations:
    categories: Kubernetes
    chartDescription: Injects generic kubernetes chaos 
spec:
  displayName: Generic Chaos
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.

  experiments:
    - sample-pod-delete
    
  keywords:
    - Kubernetes
    - Container
    - Node
    - Pod
    - Disk
    - IO
    - Filesystem
    - Network
    - CPU
    - Memory
    - Service
  maintainers:
    - name: jinjiawang
      email: jinjiawang@eric.com
  minKubeVersion: 1.12.0
  provider:
    name: Eric
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/ 
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/jinjiaw/chaos-charts/master/charts/sample-category/experiments.yaml
